//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH_Banking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JH_Banking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[spCreateBankAccount]
        ///	@Balance real,
        ///	@UserId int
        ///AS
        ///	declare @genBankAccNum bigint
        ///	declare @genCardNum bigint
        ///Begin
        ///	select @genBankAccNum = Max(AccNum)+1  from BankAccounts
        ///	select @genCardNum = cast(Max(CardNum)as bigint)  +1  from BankAccounts
        ///
        ///	INSERT INTO [dbo].[BankAccounts]
        ///		   (
        ///			AccNum,
        ///			Balance,
        ///			CardNum,
        ///			UserId
        ///		   )
        ///     VALUES
        ///           (
        ///			@genBankAccNum,
        ///			@Balance,
        ///			@genCardNum,
        ///			@UserId
        ///			)
        ///End
        ///
        ///.
        /// </summary>
        internal static string spCreateBankAccount {
            get {
                return ResourceManager.GetString("spCreateBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[spCreateUser]
        ///	@FirstName nvarchar(max),
        ///	@LastName nvarchar(max),
        ///	@PidNum nvarchar(max),
        ///	@PlaceOfBirth nvarchar(max),
        ///	@Citizenship nvarchar(max),
        ///    @Street nvarchar(max),
        ///    @NumberOfDescriptive nvarchar(max),
        ///    @Town nvarchar(max),
        ///    @Zip nvarchar(max),
        ///    @Email nvarchar(max),
        ///    @Phone nvarchar(max),
        ///    @MailStreet nvarchar(max),
        ///    @MailNumberOfDescriptive nvarchar(max),
        ///    @MailTown nvarchar(max),
        ///    @MailZip nvarchar(max),
        ///    @Password nvarchar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spCreateUser {
            get {
                return ResourceManager.GetString("spCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[spUpdateBankAccount]
        ///	@AccId int,
        ///	@Balance real
        ///	
        ///AS
        ///Begin
        ///
        ///	UPDATE [dbo].[BankAccounts]
        ///		SET Balance = @Balance
        ///		where AccId = @AccId
        ///
        ///End
        ///
        ///.
        /// </summary>
        internal static string spUpdateBankAccount {
            get {
                return ResourceManager.GetString("spUpdateBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCEDURE [dbo].[spUpdateUser]
        ///	@userId int,
        ///	@UserName nvarchar(max),
        ///	@FirstName nvarchar(max),
        ///	@LastName nvarchar(max),
        ///	@PidNum nvarchar(max),
        ///	@PlaceOfBirth nvarchar(max),
        ///	@Citizenship nvarchar(max),
        ///    @Street nvarchar(max),
        ///    @NumberOfDescriptive nvarchar(max),
        ///    @Town nvarchar(max),
        ///    @Zip nvarchar(max),
        ///    @Email nvarchar(max),
        ///    @Phone nvarchar(max),
        ///    @MailStreet nvarchar(max),
        ///    @MailNumberOfDescriptive nvarchar(max),
        ///    @MailTown nvarchar(max),
        ///    @Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spUpdateUser {
            get {
                return ResourceManager.GetString("spUpdateUser", resourceCulture);
            }
        }
    }
}
